---
base_archiving_tools:
  - arj
  - cabextract
  - file-roller
  - mpack
  - p7zip-full
  - p7zip-rar
  - rar
  - sharutils
  - unace
  - unrar
  - unzip
  - uudeview
  - zip

base_download_tools:
  - wget

base_developer_tools:
  - bat
  - tmux
  - ansible
  - ansible-lint
  - git
  - golang-go
  - htop
  - ipython3
  - python3-cachecontrol
  - python3-jmespath
  - python3-pep8
  - python3-pip
  - tree

golang_tools:
  - github.com/charmbracelet/glow@latest # Render markdown on the CLI
  - github.com/jesseduffield/lazygit@latest # simple terminal UI for git commands
  - github.com/wagoodman/dive@latest # tool for exploring each layer in a docker image
