---
# Install and configure Docker CE and Docker Compose on Ubuntu 24.04 in WSL2

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Install Docker using convenience script
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh

- name: Ensure Docker service is enabled and started
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ local_username }}"
    groups: docker
    append: true

- name: Configure Docker storage driver
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: "0644"

  notify: Restart Docker

- name: Clean up apt cache
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  changed_when: false
  register: docker_version

- name: Verify Docker Compose installation
  ansible.builtin.command: docker compose version
  changed_when: false
  register: docker_compose_version

- name: Debug Docker versions
  ansible.builtin.debug:
    msg:
      - "Docker: {{ docker_version.stdout }}"
      - "Docker Compose: {{ docker_compose_version.stdout }}"
